version: "3.9"

services:
  service-a:
    build: ./service-a
    container_name: service-a
    ports:
      - "8080:8000"   # Expose container port 8000 to host 8080
    networks:
      - chaosnet

  service-b:
    build: ./service-b
    container_name: service-b
    ports:
      - "8001:8001"
    depends_on:
      - service-a
    environment:
      - SERVICE_A_URL=http://service-a:8000/data
    networks:
      - chaosnet

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - chaosnet

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - chaosnet

networks:
  chaosnet:
    driver: bridge
