services:
  service-a:
    build: ./service-a
    container_name: service-a
    ports:
      - "8000:8000"
    networks:
      - chaosnet

  service-b:
    build: ./service-b
    container_name: service-b
    ports:
      - "8001:8001"
    depends_on:
      - service-a
    environment:
      - SERVICE_A_URL=http://service-a:8000/data
    networks:
      - chaosnet

networks:
  chaosnet:
    driver: bridge
