services:
  service-a:
    build: ./service-a
    container_name: service-a
    ports:
      - "8000:8000"
    networks:
      - chaosnet

  service-b:
    build: ./service-b
    container_name: service-b
    ports:
      - "8001:8001"
    depends_on:
      - service-a
    environment:
      - SERVICE_A_URL=http://service-a:8000/data
    networks:
      - chaosnet

networks:
  chaosnet:
    driver: bridge

grafana:
  image: grafana/grafana-oss:latest
  ports:
    - "3000:3000"
  environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin
  depends_on:
    - prometheus
